package router

import (
	"bookkeeping/internal/controller"
	"bookkeeping/internal/database"
	"bookkeeping/internal/middleware"

	"github.com/gin-gonic/gin"

	// ginSwagger "github.com/swaggo/gin-swagger"
	// gin-swagger middleware
	// swaggerFiles "github.com/swaggo/files"
	// docs is generated by Swag CLI, you have to import it
	"bookkeeping/docs"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// swagger embed files

// gin-swagger middleware
// swagger embed files

// @title           记账 API
// @version         1.0
// @description     这是一个 API 文档
// @termsOfService  http://swagger.io/terms/

// @contact.name   yym
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.basic  BasicAuth
// @externalDocs.description  OpenAPI

// @externalDocs.url          https://swagger.io/resources/open-api/

func New() *gin.Engine {
	gin.SetMode(gin.ReleaseMode)
	r := gin.Default()
	r.Use(middleware.GetUserInfo([]string{"/ping", "/api/v1/session", "/api/v1/validation_codes"})) // Use 中间件
	database.GormConnect()
	docs.SwaggerInfo.Version = "1.0"

	api := r.Group("/api")
	for _, controller := range loadControllers() {
		controller.RegisterRoutes(api)
	}

	r.GET("/api/v1/ping", controller.Ping)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}

func loadControllers() []controller.Controller {
	return []controller.Controller{
		&controller.SessionController{},
		&controller.ValidationCodeController{},
		&controller.MeController{},
		&controller.ItemController{},
	}
}
